name: Remove old artifacts

on:
  schedule:
    # Every Sunday at 1am
    - cron: '0 1 * * 0'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@ca9712b3e7e2028a11d9918944e30664a6ed5e82 # node24; v1.4.0 is still node20
      with:
        age: '1 month'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5

